# Generated by Django 2.0.3 on 2018-09-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplusapp', '0004_auto_20180918_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplususer',
            name='profile_picture',
            field=models.ImageField(default='default_profile_pic.png', upload_to=''),
        ),
    ]
