# Generated by Django 2.1.1 on 2018-09-19 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('aplusapp', '0005_auto_20180918_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aplususer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='aplususer',
            name='profile_picture',
            field=django_resized.forms.ResizedImageField(crop=None, default='default-profile-pic.jpg', force_format=None, keep_meta=True, quality=0, size=[500, 500], upload_to=''),
        ),
    ]
