# Generated by Django 2.1.1 on 2018-09-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplusapp', '0011_auto_20180923_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='aplus_id',
            field=models.CharField(max_length=250),
        ),
    ]
