# Generated by Django 2.0.3 on 2018-09-23 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplusapp', '0012_auto_20180923_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplususer',
            name='is_an_exec',
            field=models.BooleanField(default=False),
        ),
    ]
