# Generated by Django 2.0.3 on 2018-09-24 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplusapp', '0013_aplususer_is_an_exec'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
