# Generated by Django 2.1.1 on 2018-09-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplusapp', '0014_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='subjects_tutoring',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
