# Generated by Django 2.1.1 on 2018-09-24 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplusapp', '0015_auto_20180924_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
