# Generated by Django 2.0.3 on 2018-10-08 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplusapp', '0017_student_hours_of_tutoring_used_this_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='number_of_hours',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)]),
        ),
    ]
