# Generated by Django 2.0.3 on 2018-11-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplusapp', '0018_auto_20181008_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hourly_charge',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studenttutoredbytutor',
            name='tutor_rate',
            field=models.FloatField(default=0),
        ),
    ]
