# Generated by Django 2.0.3 on 2018-11-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplusapp', '0019_auto_20181109_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date_added',
            field=models.DateField(blank=True, null=True),
        ),
    ]
