# Generated by Django 2.0.3 on 2018-12-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplusapp', '0021_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplususer',
            name='is_a_student',
            field=models.BooleanField(default=False),
        ),
    ]
