# Generated by Django 2.2.3 on 2019-07-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplusapp', '0022_aplususer_is_a_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
